swagger: '2.0'
info:
  title: Bank Argent API documentation
  description: Contains all available API endpoints in this codebase
  version: '2.0.0'
  termsOfService: 'http://swagger.io/terms/'
host: localhost:3001
basePath: /api/v2
schemes:
  - http
paths:
  /user/login:
    post:
      tags:
        - User Module
      summary: Login
      description: API for Login
      parameters:
        - in: body
          name: body
          description: Login Payload
          required: true
          schema:
            $ref: '#/definitions/Login'
      produces:
        - application/json
      responses:
        '200':
          description: Login Successfully
          schema:
            $ref: '#/definitions/LoginResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /user/signup:
    post:
      tags:
        - User Module
      summary: Signup
      description: API for Signup
      parameters:
        - in: body
          name: body
          description: Signup Payload
          required: true
          schema:
            $ref: '#/definitions/User'
      produces:
        - application/json
      responses:
        '200':
          description: Signup Successfully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /user/profile:
    post:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Profile API
      description: API for fetching a user profile
      #produces:
       # - application/json
      responses:
        '200':
          description: User profile retrieved successully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
    put:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Profile API
      description: API for updating a user profile
      parameters:
        - in: body
          name: body
          description: Update user profile attributes
          required: true
          schema:
            $ref: '#/definitions/UserProfile'
      produces:
        - application/json
      responses:
        '200':
          description: User profile retrieved successully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /user/account:
    get: 
      tags:
        - Accounts and Transactions Module
      summary: Getting all the bank accounts information
      description: API for retrieving all user account
      security:
        - Bearer: []
      responses: 
        '200':
          description: All accounts retrieved successfully
          schema:
            type: array
            items:
              $ref: '#/definitions/AccountResponse'
        '401':
          description: Unauthorized user
        '500':
          description: Internal Server Error
  /account/{accountID}/transactions:
    get:
      tags:
        - Accounts and Transactions Module
      summary: List of transactions assiociated with an account for the current Month
      description: API for retrieving list of transactions assiocated with an account for the current Month
      security: 
        - Bearer: []
      parameters:
        - in: path
          name: accountID
          description: ID of an account
          required: true
          type: string
        - in: query
          name: currentMonth
          description: Filter transactions for the current month
          required: true
          type: string
      responses:
        '200':
          description: All transactions retrieved successfully
          schema: 
            type: array
            items:
              $ref: '#/definitions/TransactionsResponse'
        '401':
          description: Unauthorized user
        '404': 
          description: Account not found
        '500':
          description: Internal Server Error
  /account/{accountID}/transactions/{transactionID}:
    get:
      tags:
        - Accounts and Transactions Module
      summary: details about a transaction ( containing note, category and type )
      description: API for retrieving list of transactions assiocated with an account
      security: 
        - Bearer: []
      parameters:
        - in: path
          name: accountID
          description: ID of an account
          required: true
          type: string
        - in: path
          name: transactionID
          description: ID of a transaction
          required: true
          type: string
      responses:
        '200':
          description: Details retrieved successfully
          schema: 
            type: array
            items:
              $ref: '#/definitions/TransactionDetailsResponse'
        '401':
          description: Unauthorized user
        '404': 
          description: Transaction not found
        '500':
          description: Internal Server Error
  /transactions/{transactionID}:
    put:
      tags:
        - Accounts and Transactions Module
      summary: Update a transaction note or category
      description: API for updating the note or category of a transaction
      security:
        - Bearer: []
      parameters:
        - in: path
          name: transactionID
          description: ID of a transaction
          required: true
          type: string
        - in: body
          name: Note And Category
          description: Modify a transaction's note or category
          required: true
          schema:
            $ref: '#/definitions/TransactionNoteAndCategory'
      responses:
        '200':
          description: Note or category modified successfully
          schema:
            $ref: '#/definitions/TransactionResponseNoteAndCategory'
        '401':
          description: Unauthorized user
        '404':
          description: Transaction not found
        '500':
          description: Internal Server Error
securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
definitions:
  User:
    properties:
      email:
        type: string
        description: user email
      password:
        type: string
        description: user password
      firstName:
        type: string
        description: user first name
      lastName:
        type: string
        description: user last name
      userName:
        type: string
        description: user public name
  Login:
    properties:
      email:
        type: string
        description: user email
      password:
        type: string
        description: user password
  ApiResponse:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: object
        properties:
          id:
            type: string
          email:
            type: string
  LoginResponse:
    type: object
    properties:
      token:
        type: string
  UserProfile:
    type: object
    properties:
      userName:
        type: string
  AccountResponse:
      type: object
      properties:
        accountID:
          type: string
          description: account ID
        accountName:
          type: string
          description: account name
        accountCurrency:
          type: string
          description: account currency
        currentBalance:
          type: number
          description: current account balance
          format: double
  TransactionsResponse:
    type: object
    properties:
      transactionID: 
        type: string
        description: transaction ID
      date:
        type: string
        format: date-time
        description: date of transaction
      description:
        type: string
        description: description of transaction
      amount:
        type: number
        description: transaction amout
      balance:
        type: number
        description: available balance
        format: double
  TransactionDetailsResponse:
    type: object
    properties:
      transactionType:
        type: string
        description: type of transaction
      category:
        type: string
        description: name of the category
      note: 
        type: string
        description: user note
  TransactionNoteAndCategory:
    type: object
    properties:
      note:
        type: string
      category:
        type: string
  TransactionResponseNoteAndCategory:
    type: object
    properties:
      note:
        type: string
      category:
        type: string