swagger: '2.0'
info:
  title: Bank Argent API documentation
  description: Contains all available API endpoints in this codebase
  version: '1.0.0'
  termsOfService: 'http://swagger.io/terms/'
host: localhost:3001
basePath: /api/v1
schemes:
  - http
  
paths:
  user/{userID}/account/{accountID}/transactions:
    get:
      tags:
        - Accounts and Transactions Module
      summary: Account transactions
      description: API call for retrieving list of transactions associated with an account
      security:
        - Bearer: []
      parameters:
        - in: path
          name: accountID
          description: ID of an account
          required: true
          type: string
      responses:
        '200':
          description: All transactions retrieved successfully
          schema: 
            type: array
            items:
              $ref: '#/definitions/TransactionsResponse'
        '401':
          description: Unauthorized user
        '404': 
          description: Account not found
        '500':
          description: Internal Server Error





  user/{userID}/account/transactions/{transactionID}:
    get:
      tags:
          - Specific Transaction details Module
        summary: Account transactions details
        description: API call for retrieving the details of a transaction
        security:
          - Bearer: []
        parameters:
          - in: path
            name: accountID
            description: ID of an account
            required: true
            type: string
        responses:
          '200':
            description: The Details have been retrieved successfully 
            schema: 
              type: array
              items:
                $ref: '#/definitions/TransactionsResponse'
          '401':
            description: Unauthorized user
          '404': 
            description: Account not found
          '500':
            description: Internal Server Error





  user/{userID}/account/transactions/{transactionID}/note/{noteID}:
    put:
      tags:
        - Accounts and Transactions Module
      summary: Modify transaction's note
      description: API call for modifying a note of a transaction
      security:
        - Bearer: []
      parameters:
        - in: path
          name: transactionID
          description: ID of a transaction
          required: true
          type: string
        - in: path
          name: noteID
          description: ID of a note
          required: true
          type: string
        - in: body
          name: note
          description: Modify transaction's note
          required: true
          schema: 
            $ref: '#/definitions/TransactionNote'
      responses:
        '200':
          description: Note modified successfully
          schema:
            $ref: '#/definitions/TransactionResponseNote'
        '401':
          description: Unauthorized user
        '404':
          description: Note not modified
        '500':
          description: Internal Server Error


  user/{userID}/account/transactions/{transactionID}/category:
    put:
      tags:
        - Accounts and Transactions Module
      summary: Update transaction's category
      description: API call for updating category of transaction
      security:
        - Bearer: []
      parameters:
        - in: path
          name: transactionID
          description: ID of a transaction
          required: true
          type: string
        - in: body
          name: category
          description: Modified transaction's category
          required: true
          schema:
            $ref: '#/definitions/TransactionCategory'
      responses:
        '200':
          description: Transaction's category modified successfully
          schema: 
            $ref: '#/definitions/TransactionCategory'
        '401': 
          description: Unauthorized user
        '404': 
          description: Transaction not found
        '500': 
          description: Internal Server Error
